default: &default
  adapter: postgresql
  encoding: utf8
  url: <%= ENV.fetch("DATABASE_URL") %>
  pool: 5

development:
  <<: *default
  database: spets_development

test:
  <<: *default
  database: spets_test

production:
  <<: *default
  database: spets_production
  pool: <%= ENV.fetch('WEB_CONCURRENCY_MAX_THREADS') { 8 }.to_i %>
