default: &default
  adapter: postgresql
  encoding: utf8
  url: <%= ENV.fetch("DATABASE_URL") %>
  pool: 5

development:
  <<: *default
  database: epets_development

test:
  <<: *default
  database: epets_test

production:
  <<: *default
  database: wpets_production
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 }.to_i %>
